#!/bin/bash
DUMP=/home/$USER/dump.sql
backup(){
sudo mysqldump -A  > $DUMP
if [ $? -ne 0 ]
then
	sudo systemctl start mariadb
	backup
fi
}
backup
if [ -f $DUMP ]
then
	echo "Success! Dump is in $DUMP"
fi

